# 1) Bibliotheken importieren und Daten einlesen

In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn import metrics

df= pd.read_csv('WORK_QUERY_FOR_SPAM_HAM_DATASET.csv', sep= ';')

# 2) Übersicht Datensatz und Bereinigen

In [4]:
df.head()

text  label_num
0  Subject: enron methanol ; meter # : 988291..th...          0
1  Subject: hpl nom for january 9 , 2001..( see a...          0
2  Subject: neon retreat..ho ho ho , we ' re arou...          0
3  Subject: photoshop , windows , office . cheap ...          1
4  Subject: re : indian springs..this deal is to ...          0

In [5]:
df['label_num'].value_counts()

0    3672
1    1499
Name: label_num, dtype: int64

Der Datensatz hat zwei Variablen. 'text' und 'label_num'. 'label_num' ist die Zielvariable, 'text' enthält den Text.
Der Datensatz besteht zu ca. 30% aus Spam.

In [7]:
df.isnull().sum()

text         0
label_num    0
dtype: int64

In [8]:
blanks = []

for i,rn, sr in df.itertuples():
    if type(sr) == str:
        if sr.isspace():
            blanks.append(i)

len(blanks)

0

Keine fehlenden Werte oder Blanks

# 3) Daten transformieren

### Test und Trainingsdaten

In [21]:
x= df['text']
y= df['label_num']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [23]:
len(y_train)

3619

In [24]:
len(y_test)

1552

In [26]:
y_train.value_counts()

0    2551
1    1068
Name: label_num, dtype: int64

# 4) Modell schätzen

In [27]:
lin_svc = Pipeline([('tfidf', TfidfVectorizer()),
('cfs', LinearSVC())])

In [28]:
lin_svc.fit(x_train, y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Pipeline(steps=[('tfidf', TfidfVectorizer()), ('cfs', LinearSVC())])

# 5) Beurteilung

In [35]:
print(metrics.confusion_matrix(y_test,predictions))

[[1110   11]
 [   6  425]]


In [39]:
predictions = lin_svc.predict(x_test)
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1121
           1       0.97      0.99      0.98       431

    accuracy                           0.99      1552
   macro avg       0.98      0.99      0.99      1552
weighted avg       0.99      0.99      0.99      1552



In [40]:
print(metrics.accuracy_score(y_test,predictions))

0.9890463917525774


In [46]:
new_message = 'Congratulations! YOU are the lucky winner.'

In [48]:
lin_svc.predict([new_message])

array([1], dtype=int64)

In [58]:
second_message= 'Hey, I just wanted to say thank you for helping me out yesterday!'

In [59]:
lin_svc.predict([second_message])

array([0], dtype=int64)